version: '3.7'
services:
  gui-base:
    build:
      context: ./docker/base
    image: med-tester-gui-base

  app:
    build:
      context: ./docker/dev
    working_dir: /var/www/element
    image: med-tester-gui-dev
    ports:
      - "4200"
    volumes:
      - .:/var/www/element
    environment:
      - VIRTUAL_HOST=medtester.dev
      - VIRTUAL_PORT=4200
      - VIRTUAL_PROTO=http
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
